[build]
target = "riscv32imac-unknown-none-elf"

[target."riscv32imac-unknown-none-elf"]
rustflags = []

# not using wchisp, using the LinkE to flash
#runner = "sudo /home/lunette/.cargo/bin/wchisp flash"
